config/routes.rb
Rails.application.routes.draw do
  get 'profils/index'
  get '/profil/:profil_page_id', to: "profil#show"
  get '/', to: 'gossips#index'
  get '/welcome', to: 'gossips#index'
  get '/welcome/:first_name', to: 'gossips#index'
  get '/team', to: 'static#team'
  get '/contact', to: 'static#contact'

  resources :gossips 
  resources :profils
  



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, 
    presence: true, 
    length: { in: 3..14 }
  validates :content, presence: true

  belongs_to :user
  has_many :join_tag_with_gossips
  has_many :tags, through: :join_tag_with_gossips
end

app/models/join_tag_with_gossip.rb
class JoinTagWithGossip < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_tag_with_gossips
  has_many :gossips, through: :join_tag_with_gossips
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception # Prevent CSRF attacks by raising an exception.
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
    def index
      puts "$" * 60
      puts "Voici le param de la page welcome :"
      puts  params[:first_name]
      puts "$" * 60    
      @first_name = params[:first_name]
      @gossips = Gossip.all
      
    end

    def show
        puts "$" * 60
        puts "Voici le params de la page show :"
        puts  params[:id]
        puts "$" * 60    
        @id = params[:id]
        @gossip = Gossip.find(@id)
    end

    def new
      @gossip = Gossip.find(1)        
      
    end

    def create
      
      @user = User.find(11)
      puts "$" * 60
      puts "Voici les params de la page create :"
      puts params[:title]
      puts params[:content]      
      puts "$" * 60
      @gossip = Gossip.new(title:params[:title],content:params[:content],user:@user)
      
      if @gossip.save
        flash[:success] = "Le gossip a été créé correctement."
        redirect_to gossips_path
      else
        render 'gossips/new'
      end

    end
  
end

app/controllers/profils_controller.rb
class ProfilsController < ApplicationController
  def index

  end
  def show
    @profil_page_id = params[:id]
    @gossip = Gossip.find(@profil_page_id)
    puts "%"*60
    puts @profil_page_id
    puts params
    puts "%"*60
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def team

  end
  
  def contact

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/profils_helper.rb
module ProfilsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/gossips/alert.html.erb
<% if @gossip.errors.any? %>
    <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
      <ul>
        <% @gossip.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>

app/views/gossips/index.html.erb
<!-- test si ya pas d'erreur affiche ce message -->
<% if flash[:success] %>
  <div class="success">
    <div class="alert alert-success %> alert-dismissible fade show" role="alert">
      <%= flash[:success] %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
<% end %>

<div class="jumbotron">
  <div class="container">
    <h1 class="display-3">Welcome <%= @first_name %></h1>
    <p>Blablabla...</p>
    <p><%= link_to "Creer un gossip", new_gossip_path, class:"btn btn-primary btn-lg"%></p>
  </div>
</div>

<div class="container text-center">
  
  <% Gossip.all.each do |gossip| %> <%# gossips est un tableau d'objet ! %>
    <div class="row">
      <div class="col-sm-3">
        <a href="<%=profil_path(gossip.id)%>" class="list-group-item list-group-item-action list-group-item-secondary">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" class="img-circle" height="30" width="30" alt="Avatar"><path d="M304 128a80 80 0 1 0 -160 0 80 80 0 1 0 160 0zM96 128a128 128 0 1 1 256 0A128 128 0 1 1 96 128zM49.3 464H398.7c-8.9-63.3-63.3-112-129-112H178.3c-65.7 0-120.1 48.7-129 112zM0 482.3C0 383.8 79.8 304 178.3 304h91.4C368.2 304 448 383.8 448 482.3c0 16.4-13.3 29.7-29.7 29.7H29.7C13.3 512 0 498.7 0 482.3z"/></svg>
            <%= gossip.user.first_name %><br/>
            <!--<%= link_to "profil", "/profil/#{gossip.id}"%> #ne peux pas etre utilisé dans une balise <a>-->
        </a>
      </div>
      <div class="col-sm-9">
        <a href="<%=gossip_path(gossip.id)%>" class="list-group-item list-group-item-action list-group-item-secondary">
          <%# on utilise l'id de l'objet gossip pour diriger vers la nouvelle page, cependant cela n'est pas suffisant, on fera que gossip.1, on doit utiliser as: 'gossip' on definit la lien /gossip/:id comme gossip, quon réutilise dans gossip_path.%>   
          <%# on pourrait aussi utiliser link_to "potin", "/gossip/#{gossip.id}", l'importance est d'utiliser l'id de gossip pour rédiriger à la bonne page%>
          <p><%= gossip.title %><br/> </p>                    
        </a>
      </div>
    </div>    
  <% end %> 
  
</div>

app/views/gossips/new.html.erb
<html>
  <body>
    <!-- test si ya erreur affiche ce message -->
    <% if @gossip.errors.any? %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Echec !</strong>
        <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
        <ul>
          <% @gossip.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>        
      </div>  
    <% end %>

    <!-- ... -->
    <h1>Créer un potin</h1>
    <%= form_tag gossips_path, method: "create" do %>

      <%= label_tag 'Title :' %>
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
      <%= text_field_tag 'title', "test"  %>
      <br /> <br />

      <%= label_tag 'content :' %>
      <%= text_area_tag 'content', "teeeeeeeeest" %>
      <br /> <br />   
      
      <%= submit_tag "Submit" %>

    <% end %>

    <!-- ... -->
    

  </body>
</html>

app/views/gossips/show.html.erb
<h1>Gossip#show</h1>
<p>Find me in app/views/gossip/show.html.erb</p>

<p>
  Title : <%= @gossip.title %><br/>
  Content : <%= @gossip.content %><br/>
  Autheur : <%= @gossip.user.first_name %> --><%= link_to "son profil", "/profil/#{@id}"%>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>

    <%# ajout de bootstrap %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  </head>

  <body data-turbo="false">
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.6/dist/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/welcome">The gossip project</a>
      <%# link_to "The gossip project", welcome_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Contact", contact_path, class: "nav-link" %>
            <%#<a class="nav-link" href="/contact">Contact</a> %>
          </li>
          <li class="nav-item">
            <%= link_to "Team", team_path, class: "nav-link" %>
            <%# <a class="nav-link" href="/team">Team</a> %>
          </li>
        </ul>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/profils/index.html.erb
<h1>Profils#index</h1>
<p>Find me in app/views/profils/index.html.erb</p>

app/views/profils/show.html.erb
<h1>Profil#show</h1>
<p>Find me in app/views/profil/show.html.erb</p>

first_name : <%= Gossip.find(@profil_page_id).user.first_name %><br/>
last_name : <%= Gossip.find(@profil_page_id).user.last_name %><br/>
description : <%= Gossip.find(@profil_page_id).user.description %><br/>
email : <%= Gossip.find(@profil_page_id).user.email %><br/>
age : <%= Gossip.find(@profil_page_id).user.age %><br/>
city : <%= Gossip.find(@profil_page_id).user.city.name %><br/>